### ISSUE TITLE
index.html codes

### ISSUE THREAD

**Issue by EdwardT98** [MTM6330-F18/final-fantasticFour-2#30]

**Comment by EdwardT98** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="./css/min/main.css">
    <title>IMD</title>
</head>
<body>
    <div class="navbar">
        <div class="logo">
          <img src="./img/logo-copy.png" alt="logo">
        </div>
        <nav class="nav">
                <a href="./index.html" class="menu-item active">Home</a>
                <a href="./courses.html" class="menu-item ">Courses</a>
                <a href="./professors" class="menu-item">Professors</a>
        </nav>
      </div>

      <div class="banner">
          <img src="./img/46686541_1999899450091543_8422162041157976064_n.png" alt="banner">
      </div>

      <h1>Overview </h1>
      <p>
        This two-year Ontario College Diploma program is designed to prepare students for a variety of careers in the digital media industry. Students explore the primary elements of media project planning and development with equal importance given to the creative and the technical aspects. Strong emphasis is placed on hands-on media production through courses in web development, digital imaging, authoring, animation, photography and video. Students plan and execute individual and team-based projects and gain practical experience working with live clients. The curriculum is delivered on a variety of platforms including Apple OS X, Windows and a variety of mobile operating systems.

        Bring Your Own Device (BYOD): Students are expected to have and use a laptop or mobile computing device when registered in this on-campus program. Hardware and software specifications required by your program are outlined at http://algonquincollege.com/byod. Mobile devices/laptops and supplies can be purchased directly from Algonquin`s New Technology Store at educational rates.
        SUCCESS FACTORS
        This program is well-suited for students who:
        Are highly adaptable to today`s technology.
        Are imaginative and enjoy solving problems.
        Enjoy a hands-on approach to learning about the multimedia industry.
        Enjoy working on projects in a team-based environment.
      </p>

</body>
<nav> 
<footer>
        <div class="footer">
              <a href="./index.html" class="active">Home</a>
              <a href="./courses.html">Courses</a>
              <a href="#contact">Professors</a>
            </div>
          </footer>
        </nav>
        <div class="copyright">Fantastic 6 2018</div>

          

</html>

**Comment by shatha-khorshed** [comment]
I modified the index.html and courses.html code to make them responsive.
